WITH parametro AS (
    /* 
       Normaliza o parâmetro removendo espaços e qualquer caractere
       que não seja número (máscara de CNPJ/CPF, barras, pontos, hífens etc.).
    */
    SELECT REGEXP_REPLACE(TRIM(:CNPJ), '[^0-9]', '') AS cnpj_filtro
    FROM DUAL
)

/* =========================================================
   BLOCO 1: registros em que o CNPJ informado é o EMITENTE
   ========================================================= */
SELECT
    /* Tradução do código do tomador no CT-e */
    CASE cte.CO_TOMADOR3
        WHEN 0 THEN 'Remetente'
        WHEN 1 THEN 'Expedidor'
        WHEN 2 THEN 'Recebedor'
        WHEN 3 THEN 'Destinatário'
        ELSE 'Outros'
    END AS TIPO_TOMADOR,

    /* Indica em qual papel o CNPJ filtrado foi localizado */
    'Emitente' AS PAPEL_CNPJ_FILTRADO,

    cte.NSU,
    cte.CHAVE_ACESSO,
    cte.CO_CUF,
    cte.CO_CFOP,
    cte.CO_MOD,
    cte.CO_SERIE,
    cte.CO_NCT,
    cte.DHEMI,
    cte.CO_TPCTE,
    cte.CO_INDGLOBALIZADO,
    cte.CO_UFENV,
    cte.CO_MODAL,
    cte.CO_TPSERV,
    cte.CO_MUNINI,
    cte.XMUNINI,
    cte.CO_UFINI,
    cte.CO_MUNFIM,
    cte.XMUNFIM,
    cte.CO_UFFIM,
    cte.CO_INDIETOMA,
    cte.CO_TOMADOR3,
    cte.CO_TOMADOR4,
    cte.CO_TOMADOR4_CNPJ_CPF,
    cte.CO_TOMADOR4_IE,
    cte.CO_TOMADOR4_NOME,
    cte.CO_TOMADOR4_XLGR,
    cte.CO_TOMADOR4_NRO,
    cte.CO_TOMADOR4_XCPL,
    cte.CO_TOMADOR4_XBAIRRO,
    cte.CO_TOMADOR4_CMUN,
    cte.CO_TOMADOR4_XMUN,
    cte.CO_TOMADOR4_CEP,
    cte.CO_TOMADOR4_UF,
    cte.CO_TOMADOR4_CPAIS,
    cte.CO_TOMADOR4_XPAIS,
    cte.EMIT_CO_CNPJ,
    cte.EMIT_CO_EI,
    cte.EMIT_CO_EIST,
    cte.EMIT_XNOME,
    cte.EMIT_XLGR,
    cte.EMIT_NRO,
    cte.EMIT_XCPL,
    cte.EMIT_XBAIRRO,
    cte.EMIT_CO_MUN,
    cte.EMIT_MUN,
    cte.EMIT_CEP,
    cte.EMIT_UF,
    cte.REM_CNPJ_CPF,
    cte.REM_IE,
    cte.REM_XNOME,
    cte.REM_XLGR,
    cte.REM_NRO,
    cte.REM_XCPL,
    cte.REM_XBAIRRO,
    cte.REM_CMUN,
    cte.REM_XMUN,
    cte.REM_CEP,
    cte.REM_UF,
    cte.REM_CPAIS,
    cte.REM_XPAIS,
    cte.EXP_CO_CNPJ_CPF,
    cte.EXP_CO_EI,
    cte.EXP_XNOME,
    cte.EXP_XLGR,
    cte.EXP_NRO,
    cte.EXP_XCPL,
    cte.EXP_XBAIRRO,
    cte.EXP_CO_MUN,
    cte.EXP_MUN,
    cte.EXP_CEP,
    cte.EXP_UF,
    cte.EXP_CO_PAIS,
    cte.RECEB_CNPJ_CPF,
    cte.RECEB_IE,
    cte.RECEB_XNOME,
    cte.RECEB_XLGR,
    cte.RECEB_NRO,
    cte.RECEB_XCPL,
    cte.RECEB_XBAIRRO,
    cte.RECEB_CMUN,
    cte.RECEB_XMUN,
    cte.RECEB_CEP,
    cte.RECEB_UF,
    cte.RECEB_CPAIS,
    cte.RECEB_XPAIS,
    cte.DEST_CNPJ_CPF,
    cte.DEST_IE,
    cte.DEST_XNOME,
    cte.DEST_ISUF,
    cte.DEST_XLGR,
    cte.DEST_NRO,
    cte.DEST_XCPL,
    cte.DEST_XBAIRRO,
    cte.DEST_CMUN,
    cte.DEST_XMUN,
    cte.DEST_CEP,
    cte.DEST_UF,
    cte.DEST_CPAIS,
    cte.DEST_XPAIS,
    cte.PREST_VTPREST,
    cte.PREST_VREC,
    cte.ICMS_CST,
    cte.ICMS_VBC,
    cte.ICMS_PICMS,
    cte.ICMS_VICMS,
    cte.ICMS_PREDBC,
    cte.ICMS_VBCSTRET,
    cte.ICMS_VICMSSTRET,
    cte.ICMS_PICMSSTRET,
    cte.ICMS_VCRED,
    cte.ICMS_PREDBCOUTRAUF,
    cte.ICMS_VBCOUTRAUF,
    cte.ICMS_PICMSOUTRAUF,
    cte.ICMS_VICMSOUTRAUF,
    cte.ICMS_INDSN,
    cte.ICMS_VTOTTRIB,
    cte.ICMS_INFADFISCO,
    cte.ICMS_VBCUFFIM,
    cte.ICMS_PFCPUFFIM,
    cte.ICMS_PICMSUFFIM,
    cte.ICMS_PICMSINTER,
    cte.ICMS_VFCPUFFIM,
    cte.ICMS_VICMSUFFIM,
    cte.ICMS_VICMSUFINI,
    cte.INFPROT_CSTAT,
    cte.TP_EVENTO,
    cte.IN_SCHEMA,
    cte.DT_GRAVACAO,
    cte.TP_EMIS
FROM bi.fato_cte_detalhe cte
CROSS JOIN parametro p
WHERE REGEXP_REPLACE(cte.EMIT_CO_CNPJ, '[^0-9]', '') = p.cnpj_filtro

UNION ALL

/* ==========================================================
   BLOCO 2: registros em que o CNPJ informado é o REMETENTE
   Só entra aqui se NÃO tiver batido antes como EMITENTE
   ========================================================== */
SELECT
    CASE cte.CO_TOMADOR3
        WHEN 0 THEN 'Remetente'
        WHEN 1 THEN 'Expedidor'
        WHEN 2 THEN 'Recebedor'
        WHEN 3 THEN 'Destinatário'
        ELSE 'Outros'
    END AS TIPO_TOMADOR,

    'Remetente' AS PAPEL_CNPJ_FILTRADO,

    cte.NSU,
    cte.CHAVE_ACESSO,
    cte.CO_CUF,
    cte.CO_CFOP,
    cte.CO_MOD,
    cte.CO_SERIE,
    cte.CO_NCT,
    cte.DHEMI,
    cte.CO_TPCTE,
    cte.CO_INDGLOBALIZADO,
    cte.CO_UFENV,
    cte.CO_MODAL,
    cte.CO_TPSERV,
    cte.CO_MUNINI,
    cte.XMUNINI,
    cte.CO_UFINI,
    cte.CO_MUNFIM,
    cte.XMUNFIM,
    cte.CO_UFFIM,
    cte.CO_INDIETOMA,
    cte.CO_TOMADOR3,
    cte.CO_TOMADOR4,
    cte.CO_TOMADOR4_CNPJ_CPF,
    cte.CO_TOMADOR4_IE,
    cte.CO_TOMADOR4_NOME,
    cte.CO_TOMADOR4_XLGR,
    cte.CO_TOMADOR4_NRO,
    cte.CO_TOMADOR4_XCPL,
    cte.CO_TOMADOR4_XBAIRRO,
    cte.CO_TOMADOR4_CMUN,
    cte.CO_TOMADOR4_XMUN,
    cte.CO_TOMADOR4_CEP,
    cte.CO_TOMADOR4_UF,
    cte.CO_TOMADOR4_CPAIS,
    cte.CO_TOMADOR4_XPAIS,
    cte.EMIT_CO_CNPJ,
    cte.EMIT_CO_EI,
    cte.EMIT_CO_EIST,
    cte.EMIT_XNOME,
    cte.EMIT_XLGR,
    cte.EMIT_NRO,
    cte.EMIT_XCPL,
    cte.EMIT_XBAIRRO,
    cte.EMIT_CO_MUN,
    cte.EMIT_MUN,
    cte.EMIT_CEP,
    cte.EMIT_UF,
    cte.REM_CNPJ_CPF,
    cte.REM_IE,
    cte.REM_XNOME,
    cte.REM_XLGR,
    cte.REM_NRO,
    cte.REM_XCPL,
    cte.REM_XBAIRRO,
    cte.REM_CMUN,
    cte.REM_XMUN,
    cte.REM_CEP,
    cte.REM_UF,
    cte.REM_CPAIS,
    cte.REM_XPAIS,
    cte.EXP_CO_CNPJ_CPF,
    cte.EXP_CO_EI,
    cte.EXP_XNOME,
    cte.EXP_XLGR,
    cte.EXP_NRO,
    cte.EXP_XCPL,
    cte.EXP_XBAIRRO,
    cte.EXP_CO_MUN,
    cte.EXP_MUN,
    cte.EXP_CEP,
    cte.EXP_UF,
    cte.EXP_CO_PAIS,
    cte.RECEB_CNPJ_CPF,
    cte.RECEB_IE,
    cte.RECEB_XNOME,
    cte.RECEB_XLGR,
    cte.RECEB_NRO,
    cte.RECEB_XCPL,
    cte.RECEB_XBAIRRO,
    cte.RECEB_CMUN,
    cte.RECEB_XMUN,
    cte.RECEB_CEP,
    cte.RECEB_UF,
    cte.RECEB_CPAIS,
    cte.RECEB_XPAIS,
    cte.DEST_CNPJ_CPF,
    cte.DEST_IE,
    cte.DEST_XNOME,
    cte.DEST_ISUF,
    cte.DEST_XLGR,
    cte.DEST_NRO,
    cte.DEST_XCPL,
    cte.DEST_XBAIRRO,
    cte.DEST_CMUN,
    cte.DEST_XMUN,
    cte.DEST_CEP,
    cte.DEST_UF,
    cte.DEST_CPAIS,
    cte.DEST_XPAIS,
    cte.PREST_VTPREST,
    cte.PREST_VREC,
    cte.ICMS_CST,
    cte.ICMS_VBC,
    cte.ICMS_PICMS,
    cte.ICMS_VICMS,
    cte.ICMS_PREDBC,
    cte.ICMS_VBCSTRET,
    cte.ICMS_VICMSSTRET,
    cte.ICMS_PICMSSTRET,
    cte.ICMS_VCRED,
    cte.ICMS_PREDBCOUTRAUF,
    cte.ICMS_VBCOUTRAUF,
    cte.ICMS_PICMSOUTRAUF,
    cte.ICMS_VICMSOUTRAUF,
    cte.ICMS_INDSN,
    cte.ICMS_VTOTTRIB,
    cte.ICMS_INFADFISCO,
    cte.ICMS_VBCUFFIM,
    cte.ICMS_PFCPUFFIM,
    cte.ICMS_PICMSUFFIM,
    cte.ICMS_PICMSINTER,
    cte.ICMS_VFCPUFFIM,
    cte.ICMS_VICMSUFFIM,
    cte.ICMS_VICMSUFINI,
    cte.INFPROT_CSTAT,
    cte.TP_EVENTO,
    cte.IN_SCHEMA,
    cte.DT_GRAVACAO,
    cte.TP_EMIS
FROM bi.fato_cte_detalhe cte
CROSS JOIN parametro p
WHERE REGEXP_REPLACE(cte.REM_CNPJ_CPF, '[^0-9]', '') = p.cnpj_filtro
  AND REGEXP_REPLACE(cte.EMIT_CO_CNPJ, '[^0-9]', '') <> p.cnpj_filtro

UNION ALL

/* ==============================================================
   BLOCO 3: registros em que o CNPJ informado é o DESTINATÁRIO
   Só entra aqui se NÃO tiver batido antes como EMITENTE/REMETENTE
   ============================================================== */
SELECT
    CASE cte.CO_TOMADOR3
        WHEN 0 THEN 'Remetente'
        WHEN 1 THEN 'Expedidor'
        WHEN 2 THEN 'Recebedor'
        WHEN 3 THEN 'Destinatário'
        ELSE 'Outros'
    END AS TIPO_TOMADOR,

    'Destinatário' AS PAPEL_CNPJ_FILTRADO,

    cte.NSU,
    cte.CHAVE_ACESSO,
    cte.CO_CUF,
    cte.CO_CFOP,
    cte.CO_MOD,
    cte.CO_SERIE,
    cte.CO_NCT,
    cte.DHEMI,
    cte.CO_TPCTE,
    cte.CO_INDGLOBALIZADO,
    cte.CO_UFENV,
    cte.CO_MODAL,
    cte.CO_TPSERV,
    cte.CO_MUNINI,
    cte.XMUNINI,
    cte.CO_UFINI,
    cte.CO_MUNFIM,
    cte.XMUNFIM,
    cte.CO_UFFIM,
    cte.CO_INDIETOMA,
    cte.CO_TOMADOR3,
    cte.CO_TOMADOR4,
    cte.CO_TOMADOR4_CNPJ_CPF,
    cte.CO_TOMADOR4_IE,
    cte.CO_TOMADOR4_NOME,
    cte.CO_TOMADOR4_XLGR,
    cte.CO_TOMADOR4_NRO,
    cte.CO_TOMADOR4_XCPL,
    cte.CO_TOMADOR4_XBAIRRO,
    cte.CO_TOMADOR4_CMUN,
    cte.CO_TOMADOR4_XMUN,
    cte.CO_TOMADOR4_CEP,
    cte.CO_TOMADOR4_UF,
    cte.CO_TOMADOR4_CPAIS,
    cte.CO_TOMADOR4_XPAIS,
    cte.EMIT_CO_CNPJ,
    cte.EMIT_CO_EI,
    cte.EMIT_CO_EIST,
    cte.EMIT_XNOME,
    cte.EMIT_XLGR,
    cte.EMIT_NRO,
    cte.EMIT_XCPL,
    cte.EMIT_XBAIRRO,
    cte.EMIT_CO_MUN,
    cte.EMIT_MUN,
    cte.EMIT_CEP,
    cte.EMIT_UF,
    cte.REM_CNPJ_CPF,
    cte.REM_IE,
    cte.REM_XNOME,
    cte.REM_XLGR,
    cte.REM_NRO,
    cte.REM_XCPL,
    cte.REM_XBAIRRO,
    cte.REM_CMUN,
    cte.REM_XMUN,
    cte.REM_CEP,
    cte.REM_UF,
    cte.REM_CPAIS,
    cte.REM_XPAIS,
    cte.EXP_CO_CNPJ_CPF,
    cte.EXP_CO_EI,
    cte.EXP_XNOME,
    cte.EXP_XLGR,
    cte.EXP_NRO,
    cte.EXP_XCPL,
    cte.EXP_XBAIRRO,
    cte.EXP_CO_MUN,
    cte.EXP_MUN,
    cte.EXP_CEP,
    cte.EXP_UF,
    cte.EXP_CO_PAIS,
    cte.RECEB_CNPJ_CPF,
    cte.RECEB_IE,
    cte.RECEB_XNOME,
    cte.RECEB_XLGR,
    cte.RECEB_NRO,
    cte.RECEB_XCPL,
    cte.RECEB_XBAIRRO,
    cte.RECEB_CMUN,
    cte.RECEB_XMUN,
    cte.RECEB_CEP,
    cte.RECEB_UF,
    cte.RECEB_CPAIS,
    cte.RECEB_XPAIS,
    cte.DEST_CNPJ_CPF,
    cte.DEST_IE,
    cte.DEST_XNOME,
    cte.DEST_ISUF,
    cte.DEST_XLGR,
    cte.DEST_NRO,
    cte.DEST_XCPL,
    cte.DEST_XBAIRRO,
    cte.DEST_CMUN,
    cte.DEST_XMUN,
    cte.DEST_CEP,
    cte.DEST_UF,
    cte.DEST_CPAIS,
    cte.DEST_XPAIS,
    cte.PREST_VTPREST,
    cte.PREST_VREC,
    cte.ICMS_CST,
    cte.ICMS_VBC,
    cte.ICMS_PICMS,
    cte.ICMS_VICMS,
    cte.ICMS_PREDBC,
    cte.ICMS_VBCSTRET,
    cte.ICMS_VICMSSTRET,
    cte.ICMS_PICMSSTRET,
    cte.ICMS_VCRED,
    cte.ICMS_PREDBCOUTRAUF,
    cte.ICMS_VBCOUTRAUF,
    cte.ICMS_PICMSOUTRAUF,
    cte.ICMS_VICMSOUTRAUF,
    cte.ICMS_INDSN,
    cte.ICMS_VTOTTRIB,
    cte.ICMS_INFADFISCO,
    cte.ICMS_VBCUFFIM,
    cte.ICMS_PFCPUFFIM,
    cte.ICMS_PICMSUFFIM,
    cte.ICMS_PICMSINTER,
    cte.ICMS_VFCPUFFIM,
    cte.ICMS_VICMSUFFIM,
    cte.ICMS_VICMSUFINI,
    cte.INFPROT_CSTAT,
    cte.TP_EVENTO,
    cte.IN_SCHEMA,
    cte.DT_GRAVACAO,
    cte.TP_EMIS
FROM bi.fato_cte_detalhe cte
CROSS JOIN parametro p
WHERE REGEXP_REPLACE(cte.DEST_CNPJ_CPF, '[^0-9]', '') = p.cnpj_filtro
  AND REGEXP_REPLACE(cte.EMIT_CO_CNPJ, '[^0-9]', '') <> p.cnpj_filtro
  AND REGEXP_REPLACE(cte.REM_CNPJ_CPF, '[^0-9]', '') <> p.cnpj_filtro

UNION ALL

/* ==========================================================
   BLOCO 4: registros em que o CNPJ informado é o TOMADOR
   Só entra aqui se NÃO tiver batido antes nos blocos anteriores
   ========================================================== */
SELECT
    CASE cte.CO_TOMADOR3
        WHEN 0 THEN 'Remetente'
        WHEN 1 THEN 'Expedidor'
        WHEN 2 THEN 'Recebedor'
        WHEN 3 THEN 'Destinatário'
        ELSE 'Outros'
    END AS TIPO_TOMADOR,

    'Tomador' AS PAPEL_CNPJ_FILTRADO,

    cte.NSU,
    cte.CHAVE_ACESSO,
    cte.CO_CUF,
    cte.CO_CFOP,
    cte.CO_MOD,
    cte.CO_SERIE,
    cte.CO_NCT,
    cte.DHEMI,
    cte.CO_TPCTE,
    cte.CO_INDGLOBALIZADO,
    cte.CO_UFENV,
    cte.CO_MODAL,
    cte.CO_TPSERV,
    cte.CO_MUNINI,
    cte.XMUNINI,
    cte.CO_UFINI,
    cte.CO_MUNFIM,
    cte.XMUNFIM,
    cte.CO_UFFIM,
    cte.CO_INDIETOMA,
    cte.CO_TOMADOR3,
    cte.CO_TOMADOR4,
    cte.CO_TOMADOR4_CNPJ_CPF,
    cte.CO_TOMADOR4_IE,
    cte.CO_TOMADOR4_NOME,
    cte.CO_TOMADOR4_XLGR,
    cte.CO_TOMADOR4_NRO,
    cte.CO_TOMADOR4_XCPL,
    cte.CO_TOMADOR4_XBAIRRO,
    cte.CO_TOMADOR4_CMUN,
    cte.CO_TOMADOR4_XMUN,
    cte.CO_TOMADOR4_CEP,
    cte.CO_TOMADOR4_UF,
    cte.CO_TOMADOR4_CPAIS,
    cte.CO_TOMADOR4_XPAIS,
    cte.EMIT_CO_CNPJ,
    cte.EMIT_CO_EI,
    cte.EMIT_CO_EIST,
    cte.EMIT_XNOME,
    cte.EMIT_XLGR,
    cte.EMIT_NRO,
    cte.EMIT_XCPL,
    cte.EMIT_XBAIRRO,
    cte.EMIT_CO_MUN,
    cte.EMIT_MUN,
    cte.EMIT_CEP,
    cte.EMIT_UF,
    cte.REM_CNPJ_CPF,
    cte.REM_IE,
    cte.REM_XNOME,
    cte.REM_XLGR,
    cte.REM_NRO,
    cte.REM_XCPL,
    cte.REM_XBAIRRO,
    cte.REM_CMUN,
    cte.REM_XMUN,
    cte.REM_CEP,
    cte.REM_UF,
    cte.REM_CPAIS,
    cte.REM_XPAIS,
    cte.EXP_CO_CNPJ_CPF,
    cte.EXP_CO_EI,
    cte.EXP_XNOME,
    cte.EXP_XLGR,
    cte.EXP_NRO,
    cte.EXP_XCPL,
    cte.EXP_XBAIRRO,
    cte.EXP_CO_MUN,
    cte.EXP_MUN,
    cte.EXP_CEP,
    cte.EXP_UF,
    cte.EXP_CO_PAIS,
    cte.RECEB_CNPJ_CPF,
    cte.RECEB_IE,
    cte.RECEB_XNOME,
    cte.RECEB_XLGR,
    cte.RECEB_NRO,
    cte.RECEB_XCPL,
    cte.RECEB_XBAIRRO,
    cte.RECEB_CMUN,
    cte.RECEB_XMUN,
    cte.RECEB_CEP,
    cte.RECEB_UF,
    cte.RECEB_CPAIS,
    cte.RECEB_XPAIS,
    cte.DEST_CNPJ_CPF,
    cte.DEST_IE,
    cte.DEST_XNOME,
    cte.DEST_ISUF,
    cte.DEST_XLGR,
    cte.DEST_NRO,
    cte.DEST_XCPL,
    cte.DEST_XBAIRRO,
    cte.DEST_CMUN,
    cte.DEST_XMUN,
    cte.DEST_CEP,
    cte.DEST_UF,
    cte.DEST_CPAIS,
    cte.DEST_XPAIS,
    cte.PREST_VTPREST,
    cte.PREST_VREC,
    cte.ICMS_CST,
    cte.ICMS_VBC,
    cte.ICMS_PICMS,
    cte.ICMS_VICMS,
    cte.ICMS_PREDBC,
    cte.ICMS_VBCSTRET,
    cte.ICMS_VICMSSTRET,
    cte.ICMS_PICMSSTRET,
    cte.ICMS_VCRED,
    cte.ICMS_PREDBCOUTRAUF,
    cte.ICMS_VBCOUTRAUF,
    cte.ICMS_PICMSOUTRAUF,
    cte.ICMS_VICMSOUTRAUF,
    cte.ICMS_INDSN,
    cte.ICMS_VTOTTRIB,
    cte.ICMS_INFADFISCO,
    cte.ICMS_VBCUFFIM,
    cte.ICMS_PFCPUFFIM,
    cte.ICMS_PICMSUFFIM,
    cte.ICMS_PICMSINTER,
    cte.ICMS_VFCPUFFIM,
    cte.ICMS_VICMSUFFIM,
    cte.ICMS_VICMSUFINI,
    cte.INFPROT_CSTAT,
    cte.TP_EVENTO,
    cte.IN_SCHEMA,
    cte.DT_GRAVACAO,
    cte.TP_EMIS
FROM bi.fato_cte_detalhe cte
CROSS JOIN parametro p
WHERE REGEXP_REPLACE(cte.CO_TOMADOR4_CNPJ_CPF, '[^0-9]', '') = p.cnpj_filtro
  AND REGEXP_REPLACE(cte.EMIT_CO_CNPJ, '[^0-9]', '') <> p.cnpj_filtro
  AND REGEXP_REPLACE(cte.REM_CNPJ_CPF, '[^0-9]', '') <> p.cnpj_filtro
  AND REGEXP_REPLACE(cte.DEST_CNPJ_CPF, '[^0-9]', '') <> p.cnpj_filtro;